### ISSUE TITLE
no_log set to JINJA expression failing due to expecting bool

### ISSUE THREAD

**Issue by jghal** [ansible-community/schemas#172]
I had a task with `no_log` set to a variable, which wasn't behaving as expected.

```yaml
    - name: Update yum cache
      yum:
        list: available
        update_cache: yes
      no_log: no_log_package
```
The `no_log_package` variable was set in _defaults/main.yml_ as `no_log_package: false` and I would see failures in these tasks saying that `no_log` is set t true

```
fatal: [asa-co7-498617816]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```

I found I could get rid of this by changing from a variable to a JINJA expression

```yaml
    - name: Update yum cache
      yum:
        list: available
        update_cache: yes
      no_log: "{{ no_log_package | bool }}"
```

And passing values for `no_log_package` with `-e` on the command line worked. However I now see language server errors highlighted for this task

![image](https://user-images.githubusercontent.com/53056391/159798418-2060bedd-b7df-463d-9d1d-fbafdd4f998d.png)

If I'm indeed using bad coding here to allow toggling `no_log` I'm happy to change my code per a suggested correct solution. Otherwise how can I configure the language server to ignore this?
