### ISSUE TITLE
YAML schema validation is broken out of the box (Windows)

### ISSUE THREAD

**Issue by varnav** [ansible-community/schemas#37]
Fresh Windows 10 installation (system) of 1.55.2

```
%UserProfile%\.vscode
%AppData%\Code
%LocalAppData%\Programs\Microsoft VS Code
```

were emptied before installation.

Only this extension is installed with dependencies.

I am trying to edit my task files and getting validation errors like:

```powershell
Property community.windows.win_initialize_disk is not allowed.yaml-schema: TaskModel
Missing property "action".yaml-schema: TaskModel | BeremothTaskModel
Incorrect type. Expected "array".yaml-schema: Tags | BeremothTaskModel
```

Ansible task example:

```yaml
- name: Initialize additional disk
  community.windows.win_initialize_disk:
    disk_number: 2
  tags: preinstall
```
