### ISSUE TITLE
Extend molecule schema

### ISSUE THREAD

**Issue by ikorchynskyi** [ansible-community/schemas#58]
It seems that a config for molecule scenario file [`f/molecule.yml`](../blob/master/f/molecule.json) is missing some allowed properties. For example, for the following `molecule.yml` properties dependency and lint are marked as not allowed:
```yml
---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: instance
    image: instance:latest
    registry:
      url: docker.instance.io
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/lib/systemd/systemd

provisioner:
  name: ansible

verifier:
  name: testinfra
```

Also, it seems that some platform-specific properties are also missing, for example, `command` and `tmpfs` for docker-related platforms:
![molecule-yml-check-1](https://user-images.githubusercontent.com/3692506/118612177-ce227a00-b7bd-11eb-804b-ba6909142804.png)
