### ISSUE TITLE
Property hosts being required in PlayModel and import_playbook not allowed

### ISSUE THREAD

**Issue by frock81** [ansible-community/schemas#61]
I'm using the [Ansible Language](https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible) extension in vscode that apparently uses the ansible-playbook.json schema.

There are two rules in PlayModel which I think doesn't apply:

1. Property "hosts" being required (I believe it's in line 17026)
2. Import_playbook not allowed

As an example, I believe the below is a valid playbook:

```yaml
---
- name: Import play A
  import_playbook: play-a.yml

- name: Import play B
  import_playbook: play-b.yml
```
